### ISSUE TITLE
Initialize Archaius outside Governator 

### ISSUE THREAD

**Issue by diptanu** [Netflix/iep#100]
The Governator module contains some code around loading application.properties. I think we should move this out of there, currently I am not using Governator anymore[moved to Guice 4] and hence I was not using that module but I have to copy over the initArchiaus method out of there to my main method. 

Can this be moved to any of the other modules? This doesn't seem to be related to Governator anyways.

https://github.com/Netflix/iep/blob/master/iep-governator/src/main/java/com/netflix/iep/gov/Governator.java#L135

**Comment by brharrington** [comment]
I think it will be fine to remove that method, but I don't understand what problem you are hitting. What is the issue that is requiring you to copy that method?
